import sqlite3
def Database():
    conn = sqlite3.connect(database=r'toolStore.db')
    cur = conn.cursor()
    cur.execute("CREATE TABLE IF NOT EXISTS company (N_O INTEGER PRIMARY KEY AUTOINCREMENT,ID INT, NAME TEXT, ADDRESS TEXT, CITY TEXT, PHONE_NUMBER INT, EMAIL TEXT, WEBSITE TEXT)")
    conn.commit()

    cur.execute("CREATE TABLE IF NOT EXISTS SHIPPER (No INTEGER PRIMARY KEY AUTOINCREMENT,SHIPPER_ID INT,FIRST_NAME TEXT, LAST_NAME TEXT,PHONE INTEGER)")
    conn.commit()

    cur.execute("CREATE TABLE IF NOT EXISTS STAFF (No INTEGER PRIMARY KEY AUTOINCREMENT,ID INT , NAME TEXT,GENDER TEXT,DOB TEXT, START_DATE TEXT, END_DATE TEXT, PHONE_NUMBER INTEGER, EMAIL TEXT, SALARY TEXT)")
    conn.commit()

    cur.execute("CREATE TABLE IF NOT EXISTS USER (No INTEGER PRIMARY KEY AUTOINCREMENT,ID INTEGER, LAST_NAME TEXT,FIRST_NAME TEXT,ADDRESS TEXT, PHONE TEXT, CITY TEXT, EMAIL TEXT, PASSWORD TEXT)")
    conn.commit()

    cur.execute("CREATE TABLE IF NOT EXISTS ORDERS (No INTEGER PRIMARY KEY AUTOINCREMENT,ORDER_ID TEXT,STATUS TEXT, PRODUCT_ID TEXT, SHIPPER_ID TEXT, USER_ID TEXT, STAFF_ID TEXT, QUANTITY TEXT, ORDER_DATE TEXT, ACCOUNT_BANK TEXT)")
    conn.commit()
    
    cur.execute("CREATE TABLE IF NOT EXISTS PRODUCTS (No INTEGER PRIMARY KEY AUTOINCREMENT,PRODUCT_ID TEXT, RELEASE_DATE TEXT,BRAND TEXT, SIZE TEXT, COLOR TEXT, MATERIAL TEXT, SELLING_PRICE TEXT, PRODUCT_NAME TEXT, COMPANY_ID TEXT)")
    conn.commit()


Database()